# Configuration for Starship prompt

[username]
show_always = true
style_user = "bold green"
style_root = "bold red"

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "bold blue"

[git_branch]
format = "($branch)"
style = "bold yellow"

[git_status]
format = "($status)"
