---
os_category: "linux"

# CLI & Core Essentials
base_packages:
  # Fonts
  - ttf-firacode-nerd
  - ttf-jetbrains-mono-nerd

  # CLI Tools
  - asciinema
  - fastfetch
  - fd
  - fish
  - gvfs-mtp
  - keyd
  - libmtp
  - mangohud
  - neovim
  - ntfs-3g
  - ripgrep
  - starship
  - tree
  - unrar
  - unzip
  - wget
  - wl-clipboard
  - zellij
  - zip

# Development & SDK
dev_packages:
  - android-tools
  - ansible
  - clang
  - cmake
  - delve
  - docker
  - docker-compose
  - git
  - go
  - gopls
  - godot
  - hugo
  - jdk-openjdk
  - python
  - python-pip
  - terraform

# GUI Applications
gui_packages:
  - ab-download-manager
  - ark
  - calibre
  - converseen
  - blender
  - davinci-resolve
  - evince
  - discord
  - firefox
  - gimp
  - localsend
  - obsidian
  - obs-studio
  - onlyoffice-bin
  - qemu-full
  - rog-control-center
  - steam
  - stacer
  - swtpm
  - telegram-desktop
  - virt-manager
  - vlc
  - vlc-plugins-all
  - zed

# Consolidated System Packages
sys_packages: "{{ base_packages + dev_packages + gui_packages }}"

# AUR Packages
aur_packages:
  - android-studio
  - bottles
  - flutter-bin
  - google-chrome
  - zoom

enabled_services:
  - { name: "keyd", state: "stopped", enabled: false }
