---
os_category: "linux"

base_packages:
  # Fonts
  - fonts-firacode
  - fonts-jetbrains-mono
  # CLI Tools
  - asciinema
  - fastfetch
  - fd-find
  - fish
  - keyd
  - mangohud
  - neovim
  - ripgrep
  - sshfs
  - tree
  - unrar
  - unzip
  - wget
  - wl-clipboard
  - zip

dev_packages:
  - adb
  - ansible
  - clang
  - cmake
  - default-jdk
  - docker.io
  - docker-compose
  - firefox-esr
  - git
  - godot3
  - golang
  - golang-github-go-delve-delve
  - hugo
  - libgtk-3-dev
  - mesa-utils
  - ninja-build
  - nodejs
  - npm
  - pkgconf
  - python3
  - python3-pip

gui_packages:
  - alacritty
  - blender
  - calibre
  - converseen
  - gimp
  - handbrake
  - libreoffice
  - obs-studio
  - qemu-kvm
  - steam-installer
  - swtpm
  - virt-manager
  - vlc
  - vlc-plugin-all

sys_packages: "{{ base_packages + dev_packages + gui_packages }}"

enabled_services:
  - { name: "keyd", state: "stopped", enabled: false }
