---
os_category: "linux"

base_packages:
  # Fonts
  - fira-code-fonts
  - jetbrains-mono-fonts
  # CLI Tools
  - asciinema
  - fastfetch
  - fd-find
  - fish
  - fuse-sshfs
  - keyd
  - mangohud
  - neovim
  - ripgrep
  - tree
  - unrar
  - unzip
  - wget
  - wl-clipboard
  - zip

dev_packages:
  - android-tools
  - ansible
  - clang
  - cmake
  - delve
  - docker
  - docker-compose
  - firefox
  - git
  - golang
  - godot
  - gtk3-devel
  - hugo
  - java-latest-openjdk-devel
  - mesa-utils
  - ninja-build
  - nodejs
  - npm
  - nvidia-container-toolkit
  - pkgconf
  - python3
  - python3-pip

gui_packages:
  - alacritty

sys_packages: "{{ base_packages + dev_packages + gui_packages }}"

enabled_services:
  - { name: "keyd", state: "stopped", enabled: false }
