
[env]
TERM = "xterm-256color"

[window]
blur = false
decorations = "Full"
decorations_theme_variant = "Dark"

[mouse]
bindings = [
  { mouse = "Right", action = "Copy" },
]

[font]
normal.family = "FiraCode Nerd Font"
size = 12.0

[general]
import = [
    "~/.config/alacritty/themes/themes/github_dark_colorblind.toml"
]
