---
# Ansible Galaxy Requirements
# Install via: ansible-galaxy install -r requirements.yml

collections:
  - name: kewlfft.aur
    version: ">=0.13.0"

  - name: community.general
    version: ">=8.0.0"

roles: []
