# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.
# Please make changes to /etc/nixos/configuration.nix instead.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usbhid"
    "sd_mod"
    "rtsx_usb_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/378da5e1-2749-4898-aa08-a6d3a4395300";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/ABE2-61E8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/Data" = {
    device = "/dev/disk/by-uuid/49b6342f-5010-4ec7-8f0b-11e2c191319c";
    fsType = "ext4";
    options = [ "defaults" "nofail" "x-gvfs-show" "x-gvfs-name=Data" ];
  };

  fileSystems."/mnt/Ventoy" = {
    device = "/dev/disk/by-uuid/097E-F435";
    fsType = "exfat";
    options = [ "nofail" "noauto" "x-systemd.automount" "x-gvfs-show" "x-gvfs-name=System" ];
  };

  fileSystems."/mnt/626B-4255" = {
    device = "/dev/disk/by-uuid/626B-4255";
    fsType = "vfat";
    options = [ "nosuid" "nodev" "nofail" "noauto" "x-systemd.automount"];
  };

  swapDevices = [ ];

  # Networking
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}

